# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95dba75f7cf5b176583299bbe8bfa6c2"
name = "SpeedBoost"
application_url = "https://speedboost.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_files"

[auth]
redirect_urls = [ "https://speedboost.onrender.com/api/auth" ]